services:
  - type: web
    name: blastwa
    runtime: docker # Ini yang memaksa Render pakai Docker
    plan: free
    envVars:
      - key: DB_HOST
        value: mysql-74d77aa-jumadi-c84c.g.aivencloud.com
      - key: DB_PORT
        value: "17828"
      - key: DB_USER
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_XnkKMBk9l9FHQlegs5r
      - key: DB_NAME
        value: defaultdb
      -
